package net.sb;

// Generated 29-nov-2010 23.51.05 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Configurazione generated by hbm2java
 */
@Entity
@Table(name = "configurazione", catalog = "jlotto")
public class Configurazione implements java.io.Serializable {

	private Integer id;
	private String codice;
	private String valore;

	public Configurazione() {
	}

	public Configurazione(String codice, String valore) {
		this.codice = codice;
		this.valore = valore;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "codice", nullable = false, length = 100)
	public String getCodice() {
		return this.codice;
	}

	public void setCodice(String codice) {
		this.codice = codice;
	}

	@Column(name = "valore", nullable = false, length = 500)
	public String getValore() {
		return this.valore;
	}

	public void setValore(String valore) {
		this.valore = valore;
	}

}
