package net.sb;

// Generated 29-nov-2010 23.51.05 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Estrazioni generated by hbm2java
 */
@Entity
@Table(name = "estrazioni", catalog = "jlotto")
public class Estrazioni implements java.io.Serializable {

	private Integer id;
	private Date data;
	private int ruota;
	private int estrazione1;
	private int estrazione2;
	private int estrazione3;
	private int estrazione4;
	private int estrazione5;

	public Estrazioni() {
	}

	public Estrazioni(Date data, int ruota, int estrazione1, int estrazione2,
			int estrazione3, int estrazione4, int estrazione5) {
		this.data = data;
		this.ruota = ruota;
		this.estrazione1 = estrazione1;
		this.estrazione2 = estrazione2;
		this.estrazione3 = estrazione3;
		this.estrazione4 = estrazione4;
		this.estrazione5 = estrazione5;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data", nullable = false, length = 10)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	@Column(name = "ruota", nullable = false)
	public int getRuota() {
		return this.ruota;
	}

	public void setRuota(int ruota) {
		this.ruota = ruota;
	}

	@Column(name = "estrazione_1", nullable = false)
	public int getEstrazione1() {
		return this.estrazione1;
	}

	public void setEstrazione1(int estrazione1) {
		this.estrazione1 = estrazione1;
	}

	@Column(name = "estrazione_2", nullable = false)
	public int getEstrazione2() {
		return this.estrazione2;
	}

	public void setEstrazione2(int estrazione2) {
		this.estrazione2 = estrazione2;
	}

	@Column(name = "estrazione_3", nullable = false)
	public int getEstrazione3() {
		return this.estrazione3;
	}

	public void setEstrazione3(int estrazione3) {
		this.estrazione3 = estrazione3;
	}

	@Column(name = "estrazione_4", nullable = false)
	public int getEstrazione4() {
		return this.estrazione4;
	}

	public void setEstrazione4(int estrazione4) {
		this.estrazione4 = estrazione4;
	}

	@Column(name = "estrazione_5", nullable = false)
	public int getEstrazione5() {
		return this.estrazione5;
	}

	public void setEstrazione5(int estrazione5) {
		this.estrazione5 = estrazione5;
	}

}
