package net.sb;

// Generated 29-nov-2010 23.51.05 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ruote generated by hbm2java
 */
@Entity
@Table(name = "ruote", catalog = "jlotto")
public class Ruote implements java.io.Serializable {

	private Integer id;
	private String codice;
	private String descrizione;

	public Ruote() {
	}

	public Ruote(String codice, String descrizione) {
		this.codice = codice;
		this.descrizione = descrizione;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "CODICE", nullable = false, length = 5)
	public String getCodice() {
		return this.codice;
	}

	public void setCodice(String codice) {
		this.codice = codice;
	}

	@Column(name = "DESCRIZIONE", nullable = false, length = 50)
	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

}
