package net.sb;

// Generated 29-nov-2010 23.51.05 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CalcoloNomi generated by hbm2java
 */
@Entity
@Table(name = "calcolo_nomi", catalog = "jlotto")
public class CalcoloNomi implements java.io.Serializable {

	private Integer id;
	private String carattere;
	private int valore;

	public CalcoloNomi() {
	}

	public CalcoloNomi(String carattere, int valore) {
		this.carattere = carattere;
		this.valore = valore;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "carattere", nullable = false, length = 1)
	public String getCarattere() {
		return this.carattere;
	}

	public void setCarattere(String carattere) {
		this.carattere = carattere;
	}

	@Column(name = "valore", nullable = false)
	public int getValore() {
		return this.valore;
	}

	public void setValore(int valore) {
		this.valore = valore;
	}

}
